from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BackendGateway(Protocol):
    """Outbound port required by the built-in tools."""

    def process_catalog(self) -> Any: ...
    def process(self, process_id: Any) -> Any: ...
    def context(self, process_id: Any, node_id: Any = None, family: Any = None, record_type: Any = None) -> Any: ...
    def tree(self, view: str, contract_id: int | None = None) -> Any: ...
    def machine_context(self, machine_id: int) -> Any: ...
    def contracts(self, process_id: Any = None) -> Any: ...
    def calculate_kpi(self, payload: dict[str, Any]) -> Any: ...
