from __future__ import annotations

from typing import Any, Protocol


class BpmContextPort(Protocol):
    """Read-only BPM context exposed to TREE by stable identifiers."""

    def get_process(self, process_id: str) -> dict[str, Any] | None: ...
    def get_operation(self, operation_id: str) -> dict[str, Any] | None: ...
    def get_machine(self, machine_id: str) -> dict[str, Any] | None: ...
    def get_contract(self, contract_id: str) -> dict[str, Any] | None: ...
