from __future__ import annotations

from typing import Any, Protocol


class BpmOperationalPort(Protocol):
    """Outbound capabilities owned by the BPM operational catalogue."""

    def list_processes(self) -> list[dict[str, Any]]: ...
    def create_process(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_process(self, process_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def delete_process(self, process_id: str) -> dict[str, Any]: ...
    def list_contracts(self, process_id: str | None = None, status: str | None = None) -> list[dict[str, Any]]: ...
    def get_contract(self, contract_id: str) -> dict[str, Any] | None: ...
    def create_contract(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_contract(self, contract_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def toggle_contract(self, contract_id: str) -> dict[str, Any]: ...
    def delete_contract(self, contract_id: str) -> dict[str, Any]: ...
    def get_contract_machines(self, contract_id: str) -> dict[str, Any]: ...
    def save_contract_machines(self, contract_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_machines(self, process_id=None, contract_id=None, operation_id=None, process_version_id=None, bpm_process_id=None) -> list[dict[str, Any]]: ...
    def create_machine(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_machine(self, machine_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def delete_machine(self, machine_id: str) -> dict[str, Any]: ...
    def get_machine_context(self, machine_id: str, operation_id=None, process_version_id=None) -> dict[str, Any] | None: ...
    def list_configurations(self, machine_id: int) -> list[dict[str, Any]]: ...
    def create_configuration(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_operational_catalog(self, version_id: str | None = None) -> dict[str, Any]: ...
    def get_operational_page_payload(self, page: str, params: dict[str, str] | None = None) -> dict[str, Any]: ...


class BpmContextPort(Protocol):
    """Read-only BPM context exposed to TREE by stable identifiers."""

    def get_process(self, process_id: str) -> dict[str, Any] | None: ...
    def get_operation(self, operation_id: str) -> dict[str, Any] | None: ...
    def get_machine(self, machine_id: str) -> dict[str, Any] | None: ...
    def get_contract(self, contract_id: str) -> dict[str, Any] | None: ...
