"""Explicit PostgreSQL-facing persistence ports for operational BPM data."""

from typing import Any, Protocol


class MachineRepositoryPort(Protocol):
    def create(self, nombre: str, machine_type_id: int | None = None, **fields: Any) -> dict[str, Any]: ...

    def get_all(self) -> list[dict[str, Any]]: ...

    def get_by_id(self, machine_id: int) -> dict[str, Any] | None: ...

    def update(self, machine_id: int, nombre: str, machine_type_id: int | None = None, **fields: Any) -> dict[str, Any]: ...

    def delete(self, machine_id: int) -> bool: ...


class ContractRepositoryPort(Protocol):
    def create(self, proceso_id: int, nombre: str, metrica: str | None = None, objetivo: str | None = None, bpm_process_id: str | None = None, bpm_node_id: str | None = None) -> dict[str, Any]: ...

    def get_all(self, activo: bool | None = None) -> list[dict[str, Any]]: ...

    def get_by_proceso(self, proceso_id: int, activo: bool | None = None) -> list[dict[str, Any]]: ...

    def get_by_id(self, contrato_id: int) -> dict[str, Any] | None: ...

    def update(self, contrato_id: int, nombre: str, metrica: str | None = None, objetivo: str | None = None) -> dict[str, Any]: ...

    def toggle_activo(self, contrato_id: int) -> dict[str, Any]: ...

    def delete(self, contrato_id: int) -> bool: ...


class MachineContractAssociationPort(Protocol):
    def add_maquina(self, contrato_id: int, maquina_id: int) -> bool: ...

    def remove_maquina(self, contrato_id: int, maquina_id: int) -> bool: ...

    def get_maquinas(self, contrato_id: int) -> list[dict[str, Any]]: ...


class MachineOperationConfigurationPort(Protocol):
    def get_machine_context(self, machine_id: int, operation_id: str | None = None, process_version_id: str | None = None) -> dict[str, Any] | None: ...

    def list_configurations(self, machine_id: int) -> list[dict[str, Any]]: ...

    def create_configuration(self, payload: dict[str, Any]) -> dict[str, Any]: ...
