"""Persistence ports for the BPM process-modeling aggregates.

These protocols describe the capabilities needed by the application layer.  The
current PostgreSQL implementation is still composed from the legacy repositories
behind an adapter, so this file is the stable BPM-facing contract.
"""

from typing import Any, Protocol


class ProcessRepositoryPort(Protocol):
    def list(self) -> list[dict[str, Any]]: ...

    def get(self, process_id: str) -> dict[str, Any] | None: ...

    def create(self, data: dict[str, Any]) -> dict[str, Any]: ...

    def update(self, process_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete(self, process_id: str) -> bool: ...


class NodeRepositoryPort(Protocol):
    def get(self, node_id: str) -> dict[str, Any] | None: ...

    def create(self, process_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def create_with_transition(self, process_id: str, node: dict[str, Any], transition: dict[str, Any]) -> dict[str, Any]: ...

    def update(self, node_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete(self, node_id: str) -> bool: ...

    def get_metadata(self, node_id: str) -> dict[str, Any]: ...

    def upsert_metadata(self, node_id: str, metadata: dict[str, Any]) -> dict[str, Any]: ...

    def update_stages(self, node_id: str, stages: Any) -> dict[str, Any] | None: ...


class TransitionRepositoryPort(Protocol):
    def get(self, transition_id: str) -> dict[str, Any] | None: ...

    def create(self, process_id: str, data: dict[str, Any]) -> dict[str, Any]: ...

    def update(self, transition_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete(self, transition_id: str) -> bool: ...


class OperationRepositoryPort(Protocol):
    def get(self, operation_id: str) -> dict[str, Any] | None: ...

    def update_stages(self, operation_id: str, stages: Any) -> dict[str, Any] | None: ...
