"""Inbound application port for BPM process modeling."""

from __future__ import annotations

from typing import Any, Protocol


class BpmProcessModelingPort(Protocol):
    def list_processes(self) -> Any: ...
    def create_process(self, data: dict[str, Any]) -> Any: ...
    def get_process(self, process_id: str, expand_node_id: str | None = None) -> Any: ...
    def validate_process(self, process_id: str) -> Any: ...
    def update_process(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def delete_process(self, process_id: str, cascade: bool = False) -> Any: ...
    def create_node(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def create_node_with_transition(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def update_node(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def delete_node(self, node_id: str) -> Any: ...
    def get_node_metadata(self, node_id: str) -> Any: ...
    def update_node_metadata(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def update_operation_stages(self, operation_id: str, data: dict[str, Any]) -> Any: ...
    def get_context(self, process_id: str, node_id: str | None = None, family: str | None = None, record_type: str | None = None) -> Any: ...
    def create_context_record(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def calculate_context_kpi(self, data: dict[str, Any]) -> Any: ...
    def create_transition(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def delete_transition(self, transition_id: str) -> Any: ...


__all__ = ["BpmProcessModelingPort"]
