"""Inbound application port for BPM process modeling."""

from __future__ import annotations

from typing import Any, Protocol


class BpmProcessModelingPort(Protocol):
    def list_processes(self) -> Any: ...
    def create_process(self, data: dict[str, Any]) -> Any: ...
    def get_process(self, process_id: str) -> Any: ...
    def update_process(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def list_versions(self, process_id: str) -> Any: ...
    def create_version(self, process_id: str, data: dict[str, Any]) -> Any: ...
    def get_version(self, version_id: str, expand_node_id: str | None = None) -> Any: ...
    def update_version(self, version_id: str, data: dict[str, Any]) -> Any: ...
    def create_node(self, version_id: str, data: dict[str, Any]) -> Any: ...
    def update_node(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def delete_node(self, node_id: str) -> Any: ...
    def get_node_metadata(self, node_id: str) -> Any: ...
    def update_node_metadata(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def get_operation(self, operation_id: str) -> Any: ...
    def create_operation(self, version_id: str, data: dict[str, Any]) -> Any: ...
    def delete_operation(self, operation_id: str) -> Any: ...
    def update_operation_stages(self, operation_id: str, data: dict[str, Any]) -> Any: ...
    def get_context(self, version_id: str, node_id: str | None = None, family: str | None = None, record_type: str | None = None) -> Any: ...
    def create_context_record(self, node_id: str, data: dict[str, Any]) -> Any: ...
    def calculate_context_kpi(self, data: dict[str, Any]) -> Any: ...
    def create_transition(self, version_id: str, data: dict[str, Any]) -> Any: ...
    def delete_transition(self, transition_id: str) -> Any: ...
    def validate_version(self, version_id: str) -> Any: ...


class BpmProcessModelingApplication:
    """Application-facing facade composed from an injected port."""

    def __init__(self, handler: BpmProcessModelingPort):
        self.handler = handler

    def list_processes(self): return self.handler.list_processes()
    def create_process(self, data): return self.handler.create_process(data)
    def get_process(self, process_id): return self.handler.get_process(process_id)
    def update_process(self, process_id, data): return self.handler.update_process(process_id, data)
    def list_versions(self, process_id): return self.handler.list_versions(process_id)
    def create_version(self, process_id, data): return self.handler.create_version(process_id, data)
    def get_version(self, version_id, expand_node_id=None): return self.handler.get_version(version_id, expand_node_id)
    def update_version(self, version_id, data): return self.handler.update_version(version_id, data)
    def create_node(self, version_id, data): return self.handler.create_node(version_id, data)
    def update_node(self, node_id, data): return self.handler.update_node(node_id, data)
    def delete_node(self, node_id): return self.handler.delete_node(node_id)
    def get_node_metadata(self, node_id): return self.handler.get_node_metadata(node_id)
    def update_node_metadata(self, node_id, data): return self.handler.update_node_metadata(node_id, data)
    def get_operation(self, operation_id): return self.handler.get_operation(operation_id)
    def create_operation(self, version_id, data): return self.handler.create_operation(version_id, data)
    def delete_operation(self, operation_id): return self.handler.delete_operation(operation_id)
    def update_operation_stages(self, operation_id, data): return self.handler.update_operation_stages(operation_id, data)
    def get_context(self, version_id, node_id=None, family=None, record_type=None): return self.handler.get_context(version_id, node_id, family, record_type)
    def create_context_record(self, node_id, data): return self.handler.create_context_record(node_id, data)
    def calculate_context_kpi(self, data): return self.handler.calculate_context_kpi(data)
    def create_transition(self, version_id, data): return self.handler.create_transition(version_id, data)
    def delete_transition(self, transition_id): return self.handler.delete_transition(transition_id)
    def validate_version(self, version_id): return self.handler.validate_version(version_id)


__all__ = ["BpmProcessModelingApplication", "BpmProcessModelingPort"]
