import { fetchContractMachines, saveContractMachines, updateContract } from "../../api/operational.js";
import { findContract, findProcess, getContracts, getMachines } from "../../core/operational.js";
import { setCurrentContract, setCurrentProcess } from "../../core/state.js";
import { readHashParams } from "../../core/bpm.js";
import { escapeHtml } from "../../core/utils.js";
import { bindHomeShell, createHomeShell } from "./shell.js";
import { renderDetailHeader } from "../../components/bpm-page.js";

const field = (id, label, value, tag = "input", extra = "") => `<label class="block space-y-xs"><span class="font-label-md text-label-md text-secondary">${label}</span>${tag === "textarea" ? `<textarea id="${id}" rows="4" class="w-full border border-outline rounded-lg p-sm bg-surface-container-low font-body-sm" ${extra}>${escapeHtml(value || "")}</textarea>` : `<input id="${id}" class="w-full border border-outline rounded-lg p-sm bg-surface-container-low font-body-sm" value="${escapeHtml(value || "")}" ${extra}>`}</label>`;
function buildContractMarkup(contract, machines) {
  const options = machines.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name || item.nombre || "Máquina")}</option>`).join("");
  return `<div class="max-w-5xl mx-auto space-y-xl">${renderDetailHeader({ eyebrow: "Ficha operativa", title: contract.name || "Contrato", description: "Información editable del contrato operativo.", backHref: "#/contratos", backLabel: "Volver a contratos" })}<div id="contract-detail-page-alert" class="hidden rounded-lg border px-md py-sm text-[12px]" role="status"></div><form id="contract-detail-page-form" class="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg space-y-lg" novalidate>${field("contract-page-name", "Nombre", contract.name, "input", "required")}${field("contract-page-kpi", "KPI (obligatorio)", contract.kpi_description, "input", "required")}${field("contract-page-args", "Argumentos KPI", contract.kpi_args)}${field("contract-page-function", "Función KPI", contract.kpi_function)}${field("contract-page-objective", "Objetivo", contract.objetivo, "textarea")}<label class="block space-y-xs"><span class="font-label-md text-label-md text-secondary">Máquinas asociadas</span><select id="contract-page-machines" multiple class="w-full min-h-[140px] border border-outline rounded-lg p-sm bg-surface-container-low font-body-sm">${options}</select></label><div class="flex justify-end"><button type="submit" id="contract-page-save" class="px-lg py-sm bg-primary text-on-primary text-label-md font-label-md rounded">Guardar cambios</button></div></form></div>`;
}
function readContractForm(root) { return Object.fromEntries([["name", "contract-page-name"], ["kpi_description", "contract-page-kpi"], ["kpi_args", "contract-page-args"], ["kpi_function", "contract-page-function"], ["objetivo", "contract-page-objective"]].map(([key, id]) => [key, root.querySelector(`#${id}`).value])); }
function renderContractError(root, error, success = false) { const alert = root.querySelector("#contract-detail-page-alert"); alert.textContent = success ? "Contrato actualizado." : error.message; alert.className = `rounded-lg border px-md py-sm text-[12px] ${success ? "border-green-200 bg-green-50 text-green-700" : "border-red-200 bg-red-50 text-red-700"}`; }
async function loadContractMachines(select, id) { const response = await fetchContractMachines(id); const ids = response?.data?.machineIds || []; Array.from(select.options).forEach((option) => { option.selected = ids.includes(Number(option.value)); }); }
function bindContractEvents(root, contract) { root.querySelector("#contract-detail-page-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const save = root.querySelector("#contract-page-save"); if (!form.reportValidity()) return; save.disabled = true; try { await updateContract(contract.id, readContractForm(root)); const select = root.querySelector("#contract-page-machines"); await saveContractMachines(contract.id, Array.from(select.selectedOptions).map((item) => Number(item.value))); renderContractError(root, null, true); } catch (error) { renderContractError(root, error); } finally { save.disabled = false; } }); }
export function renderContratosDetalle(state) {
  const { root, mainSlot, rightSlot } = createHomeShell(state, { rightWidthClass: "w-[560px]" }); mainSlot.innerHTML = '<div class="max-w-5xl mx-auto"><p class="text-secondary">Cargando contrato…</p></div>'; rightSlot.innerHTML = "";
  return { shellMode: "full", main: root, afterMount(mountRoot, currentState) { bindHomeShell(mountRoot); const id = readHashParams().get("contract_id"); const contract = findContract(currentState, id) || getContracts(currentState).find((item) => String(item.id) === String(id)); const main = mountRoot.querySelector("[data-shell-main]"); const right = mountRoot.querySelector("[data-shell-right]"); if (!contract) { main.innerHTML = '<div class="max-w-5xl mx-auto"><p class="text-red-700">No se encontró el contrato solicitado.</p></div>'; return; } if (contract.processId) setCurrentProcess(contract.processId); setCurrentContract(contract.id); const machines = getMachines(currentState); main.innerHTML = buildContractMarkup(contract, machines); right.innerHTML = `<div class="p-lg border-b border-outline-variant bg-surface-container-low"><p class="font-label-md text-label-md text-secondary uppercase tracking-widest">Contrato seleccionado</p><h2 class="font-headline-md text-headline-md text-primary mt-xs">${escapeHtml(contract.name || "Sin nombre")}</h2><p class="text-[12px] text-on-surface-variant mt-sm">${escapeHtml(findProcess(currentState, contract.processId)?.name || "Sin proceso")}</p></div>`; const select = mountRoot.querySelector("#contract-page-machines"); loadContractMachines(select, contract.id).catch(() => {}); bindContractEvents(mountRoot, contract); } };
}
