import { escapeHtml } from "../core/utils.js";

export function renderDetailHeader({ eyebrow, title, description, backHref, backLabel }) {
  return `<div class="michelin-page-hero michelin-page-hero--blue flex items-center justify-between gap-lg flex-wrap"><div><span class="font-label-md text-label-md text-primary tracking-widest uppercase">${escapeHtml(eyebrow)}</span><h1 class="font-display-lg text-display-lg text-on-background">${escapeHtml(title)}</h1><p class="font-body-md text-body-md text-secondary">${escapeHtml(description)}</p></div><a href="${escapeHtml(backHref)}" class="px-md py-sm border border-outline-variant text-on-surface-variant text-label-md font-label-md rounded hover:bg-surface-container">${escapeHtml(backLabel)}</a></div>`;
}

export function renderPageAlert(id) {
  return `<div id="${escapeHtml(id)}" class="hidden rounded-lg border px-md py-sm text-[12px]" role="status" aria-live="polite"></div>`;
}

export function renderBpmProcessActions(processId, bpmProcessId = processId) {
  return `<button type="button" class="px-md py-sm bg-primary text-on-primary text-label-md font-label-md rounded hover:opacity-90" data-action="process-contracts" data-process-id="${escapeHtml(processId)}">Contratos</button><button type="button" class="px-md py-sm border border-outline-variant text-on-surface-variant text-label-md font-label-md rounded hover:bg-surface-container" data-action="process-operations" data-process-id="${escapeHtml(processId)}">Operaciones</button><button type="button" class="px-md py-sm border border-outline-variant text-on-surface-variant text-label-md font-label-md rounded hover:bg-surface-container" data-action="process-detail" data-process-id="${escapeHtml(processId)}">Detalle</button><button type="button" class="px-md py-sm border border-red-200 text-red-700 text-label-md font-label-md rounded hover:bg-red-50" data-action="process-delete" data-process-id="${escapeHtml(bpmProcessId)}" aria-label="Eliminar proceso">Eliminar</button>`;
}

export function renderProcessDeleteModal() {
  return `<div id="process-delete-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/40 p-lg" role="presentation"><div class="w-full max-w-md rounded-xl bg-surface-container-lowest p-xl shadow-lg" role="dialog" aria-modal="true" aria-labelledby="process-delete-modal-title" aria-describedby="process-delete-modal-description"><h2 id="process-delete-modal-title" class="font-headline-sm text-headline-sm text-primary">Eliminar proceso</h2><p id="process-delete-modal-description" class="font-body-sm text-body-sm text-on-surface-variant mt-sm">Esta acción eliminará el proceso y su modelado BPM asociado. No se puede deshacer.</p><p id="process-delete-modal-name" class="font-title-lg text-title-lg text-primary mt-md"></p><div id="process-delete-modal-warning" class="rounded-lg border border-amber-200 bg-amber-50 px-md py-sm text-[12px] mt-md text-amber-900" role="alert">La eliminación puede borrar el modelo BPM y sus dependientes. Si existen referencias activas, la operación será bloqueada y no se eliminará nada.</div><label class="flex items-start gap-sm mt-md text-[12px] text-on-surface-variant"><input type="checkbox" id="process-delete-acknowledge" class="mt-1" /> <span>He revisado esta advertencia y confirmo que quiero solicitar la eliminación.</span></label><div id="process-delete-modal-feedback" class="hidden rounded-lg border px-md py-sm text-[12px] mt-md" role="status" aria-live="polite"></div><div class="flex justify-end gap-sm mt-lg"><button type="button" class="px-md py-sm border border-outline-variant text-on-surface-variant text-label-md font-label-md rounded" data-modal-action="cancel">Cancelar</button><button type="button" class="px-md py-sm bg-red-700 text-white text-label-md font-label-md rounded" data-modal-action="confirm" id="process-delete-confirm" disabled>Eliminar proceso</button></div></div></div>`;
}

export function renderBpmOperationDetailButton(nodeId, processId) {
  return `<button type="button" class="px-md py-sm bg-primary text-on-primary rounded text-label-md" data-action="operation-detail" data-node-id="${escapeHtml(nodeId)}" data-process-id="${escapeHtml(processId)}">Detalle</button>`;
}
